// examples/react/src/views/WatermarkDemo.tsx
import { useRef, useState } from "react";
import { WaterMark } from "../components/WaterMark";
export function WatermarkDemo() {
  // const [watermarkProps, setWatermarkProps] = useState({
  // style: {
  //   width: '500px',
  //   height: '500px',
  //   margin: '100px auto',
  //   border: '1px solid #ddd'
  // },
  //   rotate: 30,
  //   content: ['jannkjdhachaoohkbcancmamc',
  //     '哈啰 hello hi Halo 哈喽',
  //     '你好我是？？',
  //     '你好我有一个帽衫']
  // })

  const [content, setContent] = useState(['jannkjdhachaoohkbcancmamc',
    '哈啰 hello hi Halo 哈喽',
    '你好我是？？',
    '你好我有一个帽衫'])
  const [offset, setOffset] = useState<[number, number]>([0, 0])

  const watermarkRef = useRef<{
    draw: () => void
    destroy: () => void
  }>(null)
  const toggleContent1 = () => {
    setContent(['dasdadadadadadad', 'xux 199801', 'abcdefghijklmn'])
  }
  const toggleContent2 = () => {
    setContent(['你好，再见！'])
  }

  const showWaterMark = () => {
    watermarkRef.current?.draw()
  }

  const hiddenWatermark = () => {
    watermarkRef.current?.destroy()
  }

  const moveWatermark = () => {
    setOffset([100, 0])
  }
  return <WaterMark ref={watermarkRef}
    // {
    // ...watermarkProps
    // }
    style={{
      width: '500px',
      height: '500px',
      margin: '100px auto',
      border: '1px solid #ddd'
    }}
    content={content}
    offset={offset}
  >
    <div>
      <h1>asdjahdknalkdhakld</h1>
      <h2>adjlajdlajdlja</h2>
      nihao
      <button onClick={toggleContent1}>切换水印内容 1</button>
      <button onClick={toggleContent2}>切换水印内容 2</button>
      <button onClick={showWaterMark}>显示水印</button>
      <button onClick={hiddenWatermark}>隐藏水印</button>
      <button onClick={moveWatermark}>水印整体右移 100 px</button>
    </div>
  </WaterMark>
}

// examples/v2/src/views/WaterMarkDemo.vue
<template>
  <Watermark ref="waterMarkRef" :options="options" style="height: 520px; width: 666px; border: 1px solid #ddd;">
    <h1> nadhladhahdkahdkhakd </h1>
    <button @click="changeWatermark1">修改水印按钮 1</button>
    <button @click="changeWatermark2">修改水印按钮 2</button>
    <button @click="showWatermark">显示水印</button>
    <button @click="hiddenWatermark">隐藏水印水印</button>
    <button @click="destroyWatermark">销毁水印</button>
  </Watermark>
</template>

<script>
import Watermark from '../components/Watermark/index'

const defaultOptions = {
  rotate: -20,
  textAlign: 'center',
};

export default {
  name: 'WatermarkDemo',
  components: {
    Watermark
  },
  data() {
    return {
      options: {
        ...defaultOptions,
        content: ['jannkjdhachaoohkbcancmamc',
          '哈啰 hello hi Halo 哈喽',
          '你好我是？？',
          '你好我有一个帽衫']
      }
    }
  },
  methods: {
    changeWatermark1() {
      this.options = {
        ...this.options,
        content: ['adadaldadhahdkhakdha', 'xux 199801', 'abcdefghijklmn']
      }
    },
    changeWatermark2() {
      this.options = {
        ...this.options,
        content: ['你好，再见！']
      }
    },
    hiddenWatermark() {
      this.$refs.waterMarkRef?.destroy()
    },
    showWatermark() {
      this.$refs.waterMarkRef?.draw()
    },
    destroyWatermark() {
      this.$refs.waterMarkRef?.destroy()
    }
  }
}
</script>

<style scoped></style>
